group_id: org.concopilot.example
artifact_id: chat-interactor
version: 0.0.0

type: interactor
as_plugin: false

commands:
  -
    command_name: set_llm_param
    description: set parameters for the LLM
    parameters:
      -
        name: update
        type: Dict[str, Any]
        description: The parameter name-value dict, with the keys are the parameter name, and values are the parameter values.
        required: false
      -
        name: remove
        type: List[str]
        description: The parameter list to be removed.
        required: false
    response:
      -
        name: param
        type: Dict[str, Any]
        description: the updated parameter dict.
        optional: false

setup:
  pip:
    - concopilot_examples>=0.0.1
  package: concopilot_examples.interactor.chat

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  persist_history: false
  message_history_key: message_history
  hello_msg_role: cerebrum
  hello_msg_content: Hello, can I help you?
  instruction_file: null
  exit_tokens:
    - exit
