group_id: org.concopilot.basic.resource.manager
artifact_id: basic-resource-manager
version: 0.0.0

type: resource_manager
as_plugin: false

setup:
  pip:
    - concopilot
  package: concopilot.basic.resource.manager

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
