group_id: org.concopilot.basic.message.manager
artifact_id: basic-str-msg-manager
version: 0.0.0

type: message_manager
as_plugin: false

setup:
  pip:
    - concopilot>=0.0.1
  package: concopilot.basic.message.manager.strmanager

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
