group_id: org.concopilot.example
artifact_id: auto-interactor
version: 0.0.0

type: interactor
as_plugin: false

setup:
  pip:
    - concopilot_examples
  package: concopilot_examples.interactor

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  instruction_file: instruction_with_plugin_prompt.md
  with_plugin_prompt: true
  message_history_key: message_history
  message_summary_key: message_summary
  summarize_token_len: 6500

  summarizer:
    group_id: org.concopilot.example
    artifact_id: summarizer
    version: 0.0.0
